# Service #
apiVersion: v1
kind: Service
metadata:
  name: sample-istio-review
  labels:
    app: sample-istio-review
spec:
  ports:
  - port: 80
    name: http
  selector:
    app: sample-istio-review