# Deployment #
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sample-istio-review-v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sample-istio-review
        version: v1
    spec:
      containers:
      - name: sample-istio-review
        image: fewbox/sample-istio-review:v1
        ports:
        - containerPort: 80
        imagePullPolicy: InNotPresent