apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: sample-istio-review
spec:
  hosts:
    - sample-istio-review
  http:
  - match:
    - headers:
        enduser:
          exact: landpy
    route:
    - destination:
        host: sample-istio-review
        subset: v2
  - route:
    - destination:
        host: sample-istio-review
        subset: v1